### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by elcoso** [Heckie75/kodi-addon-heckies-timer#2]
Hi!
The volume sets to 100% when firing the alarm and after that, it defaults to 100% again which is inconvenient. Can you code it so that heckies uses the volume as I set it?
For example if i´m listening to music at 50% volume and I want to start another media like sounds of rain at a given time at 10% volume, I can set the start volume for the  rain sound instead of it firing at 100%. And after the timer ends it should stay at that volume (10%) or default to a value that I should be able to program.

Thanks!

**Comment by Heckie75** [comment]
Hi, 

actually you are already able to set the starting volume. Select "fade in" or "fade out" and set the high und low volume.

But I have also added the possibility to set a default value that is set when you start kodi. Furthermore, now the timer remembers the volume level that was set before the timer has been started. After the timer has been finished the addon sets the volume back to this level instead of setting it to 100%. 

I'm not sure if this is more convenient. I will try it out the next evenings and mornings when by timers run.

Cheers and happy easter

**Comment by elcoso** [comment]
Hi Heckie! thanks for the response

What is happening right now for me is that when the timer finishes it resets to 100% volume. I´ve managed to get it default to 50% by playing with some files but I think this is not the wanted behavior. 

Thanks and happy easter!

**Comment by elcoso** [comment]
Sorry, it didn´t work... It went back to 100% when timer finished even when the file was still playing in repeat. 
Can you make it to ignore the new volume after finishing? I mean, when finishing a timer, don´t make changes to the volume

Thanks!!

**Comment by Heckie75** [comment]
Have you configured the default volume in àddon settings menu?

Maybe you could also check if HTTP control is activated. 

if this doesn't work then you can uncomment line 511 in file ``timer.py`` by adding a # character like this
```
#            xbmc.executebuiltin("SetVolume(%s)" % reset_vol)
```

**Comment by elcoso** [comment]
It worked when commenting the line 511.

Is it possible to make it stay at the last volume value that ended with the timer instead of pre-configuring one?

Thanks!
