### ISSUE TITLE
[enhancement] Use current volume as starting value for fade in / out

### ISSUE THREAD

**Issue by elcoso** [Heckie75/kodi-addon-heckies-timer#3]
Hi Heckie! 
Can you help me to make the plugin use the current set volume in kodi instead of having to input it manually in the timer for fade in /out ? 

The idea would be to just having to configure the "high" slider for fade in and the "low" slider when using fade out, instead of having to input a fixed low/high starting volume when the timer starts.

Thanks!

**Comment by Heckie75** [comment]
I have updated some code. Maybe you would like to test it. There is a new option "Fade out from current" in "Fade volume" selection. 

Since the kodi python API does not allow to query the curent volume, this is done by calling the JSON-RPC API. you have to activate it. I guess that you have to activate it in "services → Webserver → Allow control of Kodi via HTTP"

**Comment by elcoso** [comment]
> I have updated some code. Maybe you would like to test it. There is a new option "Fade out from current" in "Fade volume" selection.
> 
> Since the kodi python API does not allow to query the curent volume, this is done by calling the JSON-RPC API. you have to activate it. I guess that you have to activate it in "services → Webserver → Allow control of Kodi via HTTP"
> 
> PS: Take a look at latest commit. Previous one had a bug.

Awesome!! let me try it and I will tell you how it went!

Thanks!

**Comment by elcoso** [comment]
It works perfectly! thanks!!
